INSERT INTO `character` (`id`, `name`, `img`) VALUES
	(1, 'Isaac', 'isaac.webp'),
	(2, 'Magdalene', 'magdalene.webp'),
	(3, 'Cain', 'cain.webp'),
	(4, 'Judas', 'judas.webp'),
	(5, 'Blue Baby', 'bluebaby.webp'),
	(6, 'Eve', 'eve.webp'),
	(7, 'Samson', 'samson.webp'),
	(8, 'Azazel', 'azazel.webp'),
	(9, 'Lazarus', 'lazarus.webp'),
	(10, 'Eden', 'eden.webp'),
	(11, 'The Lost', 'thelost.webp'),
	(12, 'Lilith', 'lilith.webp'),
	(13, 'Keeper', 'keeper.webp'),
	(14, 'Apollyon', 'apollyon.webp'),
	(15, 'The Forgotten', 'forgotten.webp'),
	(16, 'Bethany', 'bethany.webp'),
	(17, 'Jacob & Esau', 'jacobesau.webp'),
	(18, 'Tainted Isaac', 'tainted_isaac.webp'),
	(19, 'Tainted Magdalene', 'tainted_magdalene.webp'),
	(20, 'Tainted Cain', 'tainted_cain.webp'),
	(21, 'Tainted Judas', 'tainted_judas.webp'),
	(22, 'Tainted Blue Baby', 'tainted_bluebaby.webp'),
	(23, 'Tainted Eve', 'tainted_eve.webp'),
	(24, 'Tainted Samson', 'tainted_samson.webp'),
	(25, 'Tainted Azazel', 'tainted_azazel.webp'),
	(26, 'Tainted Lazarus', 'tainted_lazarus.webp'),
	(27, 'Tainted Eden', 'tainted_eden.webp'),
	(28, 'Tainted Lost', 'tainted_lost.webp'),
	(29, 'Tainted Lilith', 'tainted_lilith.webp'),
	(30, 'Tainted Keeper', 'tainted_keeper.webp'),
	(31, 'Tainted Apollyon', 'tainted_apollyon.webp'),
	(32, 'Tainted Forgotten', 'tainted_forgotten.webp'),
	(33, 'Tainted Bethany', 'tainted_bethany.webp'),
	(34, 'Tainted Jacob', 'tainted_jacob.webp');

INSERT INTO `boss` (`id`, `name`, `img`, `timed`) VALUES
	(1, 'Mom\'s Heart', 'momsheart.webp', 0),
	(2, 'Isaac', 'isaac.webp', 0),
	(3, 'Blue Baby', 'bluebaby.webp', 0),
	(4, 'Satan', 'satan.webp', 0),
	(5, 'The Lamb', 'thelamb.webp', 0),
	(6, 'Mother', 'mother.webp', 0),
	(7, 'The Beast', 'thebeast.webp', 0),
	(8, 'Mega satan', 'megasatan.webp', 0),
	(9, 'Ultra greed', 'ultragreed.webp', 0),
	(10, 'Ultra greedier', 'ultragreedier.webp', 0),
	(11, 'Boss rush', 'bossrush.webp', 1),
	(12, 'Hush', 'hush.webp', 1),
	(13, 'Delirium', 'delirium.webp', 1);

INSERT INTO `restriction` (`id`, `name`, `img`) VALUES
	(1, 'No using consumables (Pills, cards, runes etc.)', 'no_consumables.webp'),
	(2, 'No bombs', 'no_bombs.webp'),
	(3, 'No hearts', 'no_hearts.webp'),
	(4, 'No chests (except endgame chest)', 'no_chests.webp'),
	(5, 'No trinkets', 'no_trinkets.webp'),
	(6, 'No treasure rooms', 'no_treasurerooms.webp'),
	(7, 'No self damage', 'no_selfdmg.webp'),
	(8, 'No secret rooms', 'no_secretrooms.webp'),
	(9, 'No shops', 'no_shops.webp'),
	(10, 'No devil rooms', 'no_devilrooms.webp'),
	(11, 'No angel rooms', 'no_angelrooms.webp'),
	(12, 'No treasure rooms until a planetarium appears', 'no_treasurerooms_untilplanetarium.webp'),
	(13, 'Take all items', 'take_all_items.webp'),
	(14, 'Go to every curse room (if not lethal)', 'goto_all_curserooms.webp'),
	(15, 'Clear every room each floors', 'clear_everyrooms.webp'),
	(16, 'Use every consumables (Pills, cards, runes etc.)', 'take_all_consumables.webp');
